name: dreamflow
description: "A DreamFlow project"
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  fl_chart: 0.68.0
  google_fonts: 6.1.0
  shared_preferences: 2.3.2
  path_provider: 2.1.4
  provider: 6.1.2
  http: '^1.0.0'
  uuid: '>=3.0.0'
  pdf: ^3.8.4
  printing: ^5.9.3
  share_plus: ^6.3.1
  petitparser: ^5.4.0
  expressions: ^0.2.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.4.0

flutter:
  uses-material-design: true
